### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by matteosodano** [facebookresearch/omni3d#12]
Hello,
I followed the installation instructions line by line, and they all went through without any error. However, when trying out the demo example, I get the following error:

`ImportError: /home/matteo/.local/lib/python3.8/site-packages/detectron2/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7reshapeEN3c108ArrayRefIlEE`

Here, the full traceback:
```
Traceback (most recent call last):
  File "demo/demo.py", line 12, in <module>
    from detectron2.engine import default_argument_parser, default_setup, launch
  File "/home/matteo/.local/lib/python3.8/site-packages/detectron2/engine/__init__.py", line 11, in <module>
    from .hooks import *
  File "/home/matteo/.local/lib/python3.8/site-packages/detectron2/engine/hooks.py", line 18, in <module>
    from detectron2.evaluation.testing import flatten_results_dict
  File "/home/matteo/.local/lib/python3.8/site-packages/detectron2/evaluation/__init__.py", line 2, in <module>
    from .cityscapes_evaluation import CityscapesInstanceEvaluator, CityscapesSemSegEvaluator
  File "/home/matteo/.local/lib/python3.8/site-packages/detectron2/evaluation/cityscapes_evaluation.py", line 11, in <module>
    from detectron2.data import MetadataCatalog
  File "/home/matteo/.local/lib/python3.8/site-packages/detectron2/data/__init__.py", line 4, in <module>
    from .build import (
  File "/home/matteo/.local/lib/python3.8/site-packages/detectron2/data/build.py", line 12, in <module>
    from detectron2.structures import BoxMode
  File "/home/matteo/.local/lib/python3.8/site-packages/detectron2/structures/__init__.py", line 7, in <module>
    from .masks import BitMasks, PolygonMasks, polygons_to_bitmask
  File "/home/matteo/.local/lib/python3.8/site-packages/detectron2/structures/masks.py", line 9, in <module>
    from detectron2.layers.roi_align import ROIAlign
  File "/home/matteo/.local/lib/python3.8/site-packages/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/matteo/.local/lib/python3.8/site-packages/detectron2/layers/deform_conv.py", line 11, in <module>
    from detectron2 import _C
ImportError: /home/matteo/.local/lib/python3.8/site-packages/detectron2/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7reshapeEN3c108ArrayRefIlEE
```

Any suggestion?

**Comment by gkioxari** [comment]
Hi @matteosodano. It seems that you weren't able to install detectron2 properly. 

1. Are you using conda and are you following the commands we provided? 
2. What is your `cuda` version
3. Our code should be compatible with newest versions of pytorch3d, detectron2 and pytorch. There should be no incompatibility issues with newest versions. I think the issue that you are facing is that your environment was not able to install detectron2 properly. So let's figure out why that is.

**Comment by Genevieve-tech** [comment]
I also encountered similar issues with Detectron2 and Pytorch3D, and used the following commands to install them:

- python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
- pip install 'git+https://github.com/facebookresearch/pytorch3d.git'

However, there still seemed to be incompatibility issues when I run demo.py.

**Comment by matteosodano** [comment]
Hi

1. Yes, I'm using conda with the commands you provided
2. I tried on two machines: one with cuda 11.2, another with cuda 10.2
2a. On that same machine with cuda 10.2, I was able to install everything properly and run the `demo` some weeks ago.

**Comment by gkioxari** [comment]
What were you not able to install with cuda 11?

**Comment by matteosodano** [comment]
It looks like the problem, as you suggested is detectron. All the rest gets installed succesfully.
