### ISSUE TITLE
demo.py not working properly

### ISSUE THREAD

**Issue by SwipaTheFox** [facebookresearch/omni3d#29]
I'm having trouble while running the demo.py script.

I run it by using the command provided in github:
`python demo/demo.py --config-file cubercnn://omni3d/cubercnn_DLA34_FPN.yaml --input-folder "datasets/coco_examples" --threshold 0.25 --display MODEL.WEIGHTS cubercnn://omni3d/cubercnn_DLA34_FPN.pth OUTPUT_DIR output/demo`

When i try to run it this way, i get the following message:
`Traceback (most recent call last):
  File "demo/demo.py", line 196, in <module>
    launch(
  File "c:\users\marti\source\repos\omni3d\detectron2\detectron2\engine\launch.py", line 84, in launch
    main_func(*args)
  File "demo/demo.py", line 149, in main
    model = build_model(cfg)
  File "C:\Users\marti\source\repos\omni3d\cubercnn\modeling\meta_arch\rcnn3d.py", line 253, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg, priors=priors)
  File "c:\users\marti\source\repos\omni3d\detectron2\detectron2\config\config.py", line 189, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
  File "c:\users\marti\source\repos\omni3d\detectron2\detectron2\config\config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "C:\Users\marti\source\repos\omni3d\cubercnn\modeling\meta_arch\rcnn3d.py", line 30, in from_config
    backbone = build_backbone(cfg, priors=priors)
  File "C:\Users\marti\source\repos\omni3d\cubercnn\modeling\meta_arch\rcnn3d.py", line 270, in build_backbone
    backbone = BACKBONE_REGISTRY.get(backbone_name)(cfg, input_shape, priors)
  File "C:\Users\marti\source\repos\omni3d\cubercnn\modeling\backbone\dla.py", line 493, in build_dla_from_vision_fpn_backbone
    bottom_up = DLABackbone(cfg, input_shape)
  File "C:\Users\marti\source\repos\omni3d\cubercnn\modeling\backbone\dla.py", line 421, in __init__
    base  = dla34(pretrained=True, tricks=cfg.MODEL.DLA.TRICKS)
  File "C:\Users\marti\source\repos\omni3d\cubercnn\modeling\backbone\dla.py", line 319, in dla34
    model.load_pretrained_model(data='imagenet', name='dla34', hash='ba72cf86')
  File "C:\Users\marti\source\repos\omni3d\cubercnn\modeling\backbone\dla.py", line 304, in load_pretrained_model
    model_weights = model_zoo.load_url(model_url)
  File "C:\Users\marti\anaconda3\envs\cubercnn\lib\site-packages\torch\hub.py", line 746, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "C:\Users\marti\anaconda3\envs\cubercnn\lib\site-packages\torch\hub.py", line 611, in download_url_to_file
    u = urlopen(req)
  File "C:\Users\marti\anaconda3\envs\cubercnn\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\marti\anaconda3\envs\cubercnn\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\marti\anaconda3\envs\cubercnn\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\marti\anaconda3\envs\cubercnn\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\marti\anaconda3\envs\cubercnn\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\marti\anaconda3\envs\cubercnn\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found`

**Comment by garrickbrazil** [comment]
It's possible that the DLA weights website was temporarily down when you encountered this 404 error. Can you try again now? 

As a side note, there is no need for the demo model to load the ImageNet weights anyways, so we will fix this soon!

**Comment by SwipaTheFox** [comment]
I just tried again but it is still not working.

**Comment by garrickbrazil** [comment]
You may be running into a different issue regarding the pretrained model hub with the DLA URLs. I've tested them more extensively (DLA 34, 46, 60, 169, etc) and they seem to work from my end. It may be worth checking if you can access the URLs from your machine in general?  The model weights are hosted here: http://dl.yf.io/dla/models/imagenet/

Anyways, we've just updated the inference models to skip unnecessarily loading ImageNet pretrained weights, which should solve your problem with the demo but you will likely encounter an issue for training if the above URLs cannot load.
