### ISSUE TITLE
Failed to download https://dl.fbaipublicfiles.com/cubercnn/omni3d\category_meta.json

### ISSUE THREAD

**Issue by SwipaTheFox** [facebookresearch/omni3d#32]
When running demo.py script i get the following error:
`Failed to download https://dl.fbaipublicfiles.com/cubercnn/omni3d\category_meta.json
Traceback (most recent call last):
  File "demo/demo.py", line 196, in <module>
    launch(
  File "C:\Users\user\anaconda3\envs\cubercnn\lib\site-packages\detectron2-0.6-py3.8-win-amd64.egg\detectron2\engine\launch.py", line 84, in launch
    main_func(*args)
  File "demo/demo.py", line 157, in main
    do_test(args, cfg, model)
  File "demo/demo.py", line 49, in do_test
    category_path = util.CubeRCNNHandler._get_local_path(util.CubeRCNNHandler, category_path)
  File "C:\Users\user\Downloads\TFMRuben\omni3d-bak\omni3d\cubercnn\util\model_zoo.py", line 19, in _get_local_path
    return PathManager.get_local_path(self.CUBERCNN_PREFIX + name)
  File "C:\Users\user\anaconda3\envs\cubercnn\lib\site-packages\iopath\common\file_io.py", line 1197, in get_local_path
    bret = handler._get_local_path(path, force=force, **kwargs)
  File "C:\Users\user\anaconda3\envs\cubercnn\lib\site-packages\iopath\common\file_io.py", line 797, in _get_local_path
    cached = download(path, dirname, filename=filename)
  File "C:\Users\user\anaconda3\envs\cubercnn\lib\site-packages\iopath\common\download.py", line 58, in download
    tmp, _ = request.urlretrieve(url, filename=tmp, reporthook=hook(t))
  File "C:\Users\user\anaconda3\envs\cubercnn\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\user\anaconda3\envs\cubercnn\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\user\anaconda3\envs\cubercnn\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\user\anaconda3\envs\cubercnn\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\user\anaconda3\envs\cubercnn\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\user\anaconda3\envs\cubercnn\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\user\anaconda3\envs\cubercnn\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden`

**Comment by dhatriparakal** [comment]
How did you fix the issue? I am getting the same error when running demo.py
